"""bets_count

Revision ID: 76820de1f240
Revises: 746d6b92fdd5
Create Date: 2023-12-29 17:39:31.496520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import text

revision: str = '76820de1f240'
down_revision: Union[str, None] = '746d6b92fdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'auctions', sa.Column('bets_count', sa.Integer(), nullable=False, default=1, server_default=text('1'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'bets_count')
    # ### end Alembic commands ###
